#!/usr/bin/env node

'use strict';

var lintJs = require('./tasks/lint-js'),
    buildCss = require('./tasks/build-css');

var options = {
    package: require('./package.json'),
    manifest: require('./manifest.json'),

    // Paths
    jsPath: './js-es6',
    cssPath: './scss-3.0',
    rootPath: '.',
    taskPath: './tasks',
    testPath: './tests-es6',
    buildPath: './build',

    // Flags
    debug: false,
    rtl: false
};

Promise.all([
    buildCss([
        'components/button-group.scss'
    ], options),
    lintJs([
        options.jsPath,
        options.testPath,
        options.taskPath
   ], options),
])
    .catch(function(error) {
        console.log('error', error);
    });
